services:
  frontend:
    container_name: website
    image: zatarain/portfolio-web
    build: web
    ports:
      - 5000:5000
    depends_on:
      - backend
    volumes:
      - web-source:/web
    environment:
      API_URL: http://service:3000
      NODE_ENV: development
  backend:
    container_name: service
    image: zatarain/portfolio-api
    build: api
    ports:
      - 3000:3000
    volumes:
      - api-source:/api
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENVIRONMENT: development
      AWS_ASSUME_ROLE: ${AWS_ASSUME_ROLE}
      AWS_SESSION_NAME: api-download-yaml-cv
volumes:
  web-source:
    name: portfolio-web-source
    driver: local
    driver_opts:
      o: bind
      type: none
      device: web
  api-source:
    name: portfolio-api-source
    driver: local
    driver_opts:
      o: bind
      type: none
      device: api
