import type { Meta, StoryObj } from '@storybook/react'
import Markdown from './index'

const meta: Meta<typeof Markdown> = {
  title: 'Example/Markdown',
  component: Markdown,
  parameters: {
    // Optional parameter to center the component in the Canvas. More info: https://storybook.js.org/docs/react/configure/story-layout
    layout: 'centered',
  },
  // This component will have an automatically generated Autodocs entry: https://storybook.js.org/docs/react/writing-docs/autodocs
  tags: ['autodocs'],
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
  argTypes: {
		className: {
			control: 'text',
			description: 'Optional. class name for the container',
		},
    content: {
			control: 'text',
			description: 'Markdown content to be rendered as HTML'
		},
  },
} satisfies Meta<typeof Markdown>;

export default meta

type Story = StoryObj<typeof Markdown>

export const MathExpressions: Story = {
	args: {
		content: `
**Theorem 1** *(Maxwell Equations).* They are a set of coupled partial differential equations that,
together with the Lorentz force law, form the foundation of classical electromagnetism,
classical optics, and electric circuits. The equations provide a mathematical model for electric,
optical, and radio technologies, such as power generation, electric motors, wireless communication,
lenses, radar, etc. They describe how electric and magnetic fields are generated by charges,
currents, and changes of the fields.

$$
	\\begin{align}
		\\nabla \\cdot \\mathbf {E} &={\\frac {\\rho }{\\varepsilon _{0}}} \\\\
		\\nabla \\cdot \\mathbf {B} &=0 \\\\
		\\nabla \\times \\mathbf {E} &=-{\\frac {\\partial \\mathbf {B} }{\\partial t}} \\\\
		\\nabla \\times \\mathbf {B} &=\\mu _{0}\\left(\\mathbf {J} +\\varepsilon _{0}{\\frac {\\partial \\mathbf {E} }{\\partial t}}\\right) \\\\
	\\end{align}
$$

**Theorem 2** *(Gauss Divergence Theorem).* Suppose $V$ is a subset of $ \\mathbb{R}^{n} $ (in the case of $n = 3$,
$V$ represents a volume in three-dimensional space) which is compact and has a piecewise smooth boundary $S$
(also indicated with $ {\\partial V=S} $). If $F$ is a continuously differentiable vector field
defined on a neighborhood of $V$, then:

$$
	\\iiint\\limits_{\\scriptstyle{V}}{\\nabla \\cdot \\mathbf{F} \\diff V} = \\oiint\\limits_{\\scriptstyle{S}}{\\mathbf{F} \\cdot \\mathbf{\\hat{n}} \\diff S}
$$
`.trim(),
	}
}
