require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metrics/MethodLength:
  Enabled: true
  Max: 30
  CountAsOne: ['array', 'heredoc', 'method_call']
Metrics/AbcSize:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - tmp/**/*
    - bin/bundle
    - vendor/bundle/**/*
    - gemfiles/vendor/bundle/**/*
    - spec/rails_helper.rb
Metrics/BlockLength:
  Exclude:
    - config/environments/*
Lint/ScriptPermission:
  Enabled: false
Rails/HttpStatus:
  Enabled: true

RSpec/ContextMethod:
  Enabled: true
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
RSpec/DescribeClass:
  Enabled: true
RSpec/EmptyHook:
  Enabled: true
RSpec/EmptyLineAfterExample:
  Enabled: true
RSpec/EmptyLineAfterFinalLet:
  Enabled: true
RSpec/ExampleLength:
  Enabled: true
RSpec/ExampleWithoutDescription:
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: false
