name: Back-end Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths: ['api/**']
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: '3.2.1'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: '3.2.1'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: bundle exec rubocop
              
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: '3.2.1'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: bundle exec rspec spec
              
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show current directory
        run: pwd
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Change to directory for API
        run: cd api
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: api/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ github.repository }}:latest
